feat(dlm):synchronize the table structure
oceanbase/odc pull request #2189
Opened 2024-04-11 03:53 UTC by guowl3

#### What type of PR is this?
type-feature

#### What this PR does / why we need it:
Synchronize the table structure based on the results from the table structure comparator. After this PR is merged, DLM tasks will support automatic table structure synchronization for both MYSQL and OB data sources.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Additional documentation e.g., usage docs, etc.:

```docs

```

2024-04-15 01:30 UTC, yizhouxw commented on server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DLMJobParameters.java
> +    private boolean isTableStructureSyncEnabled;
may remove the `is` prefix

2024-05-08 08:52 UTC, smallsheeeep requested changes

2024-05-08 08:52 UTC, smallsheeeep commented on server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
> +            try (Connection conn = targetConfig.getDataSource().getConnection()) {
Should we close or expire this DataSource?

2024-05-08 08:52 UTC, smallsheeeep commented on server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
> +                    DLMTableStructureSynchronizer.sync(
The `DLMTableStructureSynchronizer.sync()` will not throw any exception if failed to execute sync SQL script. You may need refine the code logic.

2024-05-15 03:06 UTC, smallsheeeep approved these changes

2024-05-15 03:11 UTC, krihy approved these changes
lgtm

2024-05-15 03:36 UTC, yhilmare approved these changes
lgtm

2024-05-15 03:36 UTC, merged