feat(multipledatabase): add audit events for multiple databases
oceanbase/odc pull request #2442
Opened 2024-05-21 05:39 UTC by zijiacj

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Additional documentation e.g., usage docs, etc.:

```docs

```

2024-05-21 07:05 UTC, MarkPotato777 submitted a review, later dismissed
LGTM

2024-05-21 08:01 UTC, smallsheeeep requested changes
Some comments request changes.
BTW: 
1. Should we add new APIs defined in `DatabaseChangeController` into audit?
2. We should add new notification for multiple database change in `notification-policy-metadata.yaml`.

2024-05-21 08:08 UTC, JessieWuJiexi submitted a review, later dismissed

2024-05-21 08:23 UTC, zijiacj commented on server/odc-core/src/main/resources/i18n/BusinessMessages.properties
> +com.oceanbase.odc.AuditEventAction.STOP_MULTIPLE_ASYNC_TASK=Stop multiple database Change task
![image](https://github.com/oceanbase/odc/assets/135618909/48bbd90b-7034-4f7e-a2ce-078c120ec1b7)
The last submission has been added it

2024-05-21 08:24 UTC, zijiacj commented on server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
> +com.oceanbase.odc.AuditEventAction.STOP_MULTIPLE_ASYNC_TASK=停止多庫變更任務
yes,I will do it

2024-05-21 08:28 UTC, zijiacj commented on server/starters/desktop-starter/src/main/java/com/oceanbase/odc/service/audit/DesktopAuditEventHandler.java
> +                    AuditEventAction.STOP_MULTIPLE_ASYNC_TASK,
have removed it

2024-05-24 03:32 UTC, smallsheeeep submitted a review, later dismissed

2024-05-24 03:40 UTC, JessieWuJiexi commented on server/odc-core/src/main/resources/i18n/BusinessMessages.properties
> +com.oceanbase.odc.AuditEventAction.CREATE_MULTIPLE_ASYNC_TASK=Create Multiple database Change task
Multiple -> multiple

2024-05-24 03:41 UTC, Jane201510 approved these changes

2024-05-24 12:53 UTC, zijiacj commented
> Some comments request changes. BTW:
> 
> 1. Should we add new APIs defined in `DatabaseChangeController` into audit?
> 2. We should add new notification for multiple database change in `notification-policy-metadata.yaml`.

1. have  define template create 、delete and update into audit
2. have done

2024-05-24 12:54 UTC, zijiacj commented
> Some comments request changes. BTW:
> 
> 1. Should we add new APIs defined in `DatabaseChangeController` into audit?
> 2. We should add new notification for multiple database change in `notification-policy-metadata.yaml`.

1. have  define template create 、delete and update into audit
2. have done

2024-05-27 00:43 UTC, yizhouxw approved these changes
lgtm

2024-05-27 02:14 UTC, smallsheeeep approved these changes
LGTM

2024-05-27 02:22 UTC, yhilmare approved these changes
lgtm

2024-05-27 02:22 UTC, merged