fix(taskframework): add conditional check before destroy
oceanbase/odc pull request #2745
Opened 2024-06-14 07:30 UTC by krihy

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Additional documentation e.g., usage docs, etc.:

```docs

```

2024-06-14 08:51 UTC, yizhouxw commented on server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
> +                    log.warn("Cannot destroy pod, pending is not timeout, jodId={0}, identifier={1}, podStatus={2}",
`{0}` may contains no position number ?

2024-06-14 12:07 UTC, krihy commented on server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
> +                    log.warn("Cannot destroy pod, pending is not timeout, jodId={0}, identifier={1}, podStatus={2}",
okey, done

2024-06-14 15:21 UTC, yizhouxw approved these changes
lgtm

2024-06-16 07:17 UTC, yizhouxw requested changes
may change target branch to dev/4.3.0

2024-06-17 02:02 UTC, krihy commented
> may change target branch to dev/4.3.0

okey , create a new  [PR](https://github.com/oceanbase/odc/pull/2755), and close this pr

2024-06-17 02:04 UTC, krihy commented
see new pr: https://github.com/oceanbase/odc/pull/2745

2024-06-17 02:04 UTC, closed without merging