feat(data-transfer): upgrade ob-loader-dumper to 4.2.5-RELEASE
oceanbase/odc pull request #494
Opened 2023-10-12 10:50 UTC by LuckyPickleZZ

ob-loader-dumper to 4.2.5-RELEASE

2023-10-12 10:57 UTC, yizhouxw approved these changes
lgtm

2023-10-12 13:04 UTC, yhilmare requested changes
shall we remove ignore annotation from the corresponding test cases？

2023-10-12 13:05 UTC, yhilmare approved these changes

2023-10-13 09:03 UTC, yhilmare approved these changes
lgtm

2023-10-13 09:03 UTC, merged